[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["alloc", "core", "compiler_builtins"]

[build]
target = "kikuyu-kernel.json"

[target.'cfg(target_os = "none")']
runner = "./qemu-wrapper.sh"
